version: "3.8"
services:
  authelia:
    image: authelia/authelia
    volumes:
      - authelia:/config
    networks:
      - traefik-public
    environment:
      - TZ=Europe/Berlin
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_mail_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_mail_password
    configs:
      - source: authelia_config
        target: /config/configuration.yml
        uid: '103'
        gid: '103'
        mode: 0440
      - source: authelia_users
        target: /config/users_database.yml
        uid: '103'
        gid: '103'
        mode: 0440
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)
        - traefik.http.routers.authelia.entrypoints=https
        - traefik.http.routers.authelia.tls=true
        - traefik.http.routers.authelia.tls.certresolver=le
        - traefik.http.services.authelia.loadbalancer.server.port=9091
        - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}  # yamllint disable-line rule:line-length
        - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
        - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email  # yamllint disable-line rule:line-length
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
networks:
  traefik-public:
    external:
      name: traefik-public
volumes:
  authelia:
secrets:
  authelia_jwt_secret:
    external: true
  authelia_session_secret:
    external: true
  authelia_mail_password:
    external: true
configs:
  authelia_config:
    external: true
  authelia_users:
    external: true