---
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
theme: dark
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: 
#default_redirection_url: https://public.nerdware.de
totp:
  issuer: example.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: "*.example.com"
      policy: two_factor
    - domain: "example.com"
      policy: two_factor
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: 
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: admin@example.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: 
    host: smtp.example.com
    port: 25
    sender: admin@example.com
...