version: '3'
services:
  oppgave:
    image: jimtim/oppgave:latest
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.oppgave-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.oppgave-http.entrypoints=http
        - traefik.http.routers.oppgave-http.middlewares=https-redirect
        - traefik.http.routers.oppgave-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.oppgave-https.entrypoints=https
        - traefik.http.routers.oppgave-https.tls=true
        - traefik.http.routers.oppgave-https.tls.certresolver=le
        - traefik.http.services.oppgave.loadbalancer.server.port=80
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
networks:
  traefik-public:
    external:
      name: traefik-public